
#
# This is free software, lisence use MIT
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream
on:
  #push:
  #  paths:
  #    - '.github/workflows/upstream.yml'
  #schedule:
  #  - cron: 30 19 * * *
  #watch:
  #  types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Syn upstream
      run: |
        rm -rf `find -maxdepth 1 -type d -name "[!.]*" ! -path "./Lean" ! -path "./immortalwrt" ! -path "./App" ! -path "./Pic"`
        git rm -r --cache *
       
        echo -e "\q" | svn co https://github.com/vison-v/OpenWrt/trunk/Immortalwrt ./Immortalwrt
        rm -rf ./immortalwrt/.svn
    
    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 0
    
    - name: Apply
      run: |
        git add .
        git commit -m "update" || true
        git push
        echo "::set-output name=status::success" >> $GITHUB_ENV
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 15
        keep_minimum_runs: 1
