#
# This is free software, lisence use MIT
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
  schedule:
    - cron: 30 19 * * *
  #watch:
  #  types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Syn upstream
      run: |
        rm -rf `find -maxdepth 1 -type d -name "[!.]*" ! -path "./Lean" ! -path "./Lienol" ! -path "./App" ! -path "./Pic"`
        git rm -r --cache *
       
        echo -e "\q" | svn co https://github.com/kiddin9/OpenWrt_x86-r2s-r4s/trunk/devices ./Garypang
        rm -rf ./Garypang/.svn
    
    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 0

    - name: Modify
      run: |
        curl -fsSL  https://raw.githubusercontent.com/vison-v/patches/main/addon.sh > ./Garypang/common/addon.sh
        curl -fsSL  https://raw.githubusercontent.com/vison-v/patches/main/addon >> ./Garypang/x86_64/.config
        sed -i '/DIY_SH="diy.sh"/a\ADD_SH="addon.sh"' ./Garypang/common/settings.ini
        sed -i '/CONFIG_PACKAGE_luci-app-gpsysupgrade=y/d' ./Garypang/common/.config
        sed -i '/PARTSIZE/s/1000/170/' ./Garypang/x86_64/.config
        sed -i '/WETRANSFER/s/true/false/' ./Garypang/common/settings.ini
        sed -i '/COWTRANSFER/s/true/false/' ./Garypang/common/settings.ini
        # sed -i 's/"10.0.0.1"/"192.168.10.1"/g' ./Garypang/common/default-settings
        sed -i 's/by GaryPang/Build By ViS0N/g' ./Garypang/common/diy.sh
        # sed -i 's/by GaryPang/Build By ViS0N/g' ./Garypang/common/diy/package/base-files/files/etc/banner
    
    - name: Apply
      run: |
        git add .
        git commit -m "update" || true
        git push
        
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 15
        keep_minimum_runs: 1
